### ISSUE TITLE
Project failed validation, please review "progeny -h"

### ISSUE THREAD

**Issue by AdrianKoshka** [darthlukan/progeny#18]
When trying to test out my swift footprint I get this error from main.py

``` bash
$ python3 main.py -f ~/git/github/adrian/progeny-footprints/swift/cli -n my_app -p ~/build/swift 
Project failed validation, please review "progeny -h"
usage: main.py [-h] [-n NAME] [-a AUTHOR] [-e EMAIL] [-l LICENSE]
               [-lang LANGUAGE] [-t PTYPE] [-vcs VCS] [-p PARENT]
               [-f FOOTPRINT]

Generate project directory structures based on templates or supplied args.

optional arguments:
  -h, --help            show this help message and exit
  -n NAME, --name NAME  Your app's/project's name.
  -a AUTHOR, --author AUTHOR
                        Your name.
  -e EMAIL, --email EMAIL
                        Your email address.
  -l LICENSE, --license LICENSE
                        License shortname e.g. gpl2.
  -lang LANGUAGE, --language LANGUAGE
                        The project language.
  -t PTYPE, --type PTYPE
                        The ptype of project e.g. cli, web.
  -vcs VCS, --version-control-system VCS
                        Version Control
  -p PARENT, --parent-dir PARENT
                        The parent directory e.g. ~/projects.
  -f FOOTPRINT, --footprint FOOTPRINT
                        Provide a custom footprint.
```

The same happens if I try to do it with python2

``` bash
$ python2 main.py -f ~/git/github/adrian/progeny-footprints/swift/cli -n my_app -p ~/build/swift
Project failed validation, please review "progeny -h"
usage: main.py [-h] [-n NAME] [-a AUTHOR] [-e EMAIL] [-l LICENSE]
               [-lang LANGUAGE] [-t PTYPE] [-vcs VCS] [-p PARENT]
               [-f FOOTPRINT]

Generate project directory structures based on templates or supplied args.

optional arguments:
  -h, --help            show this help message and exit
  -n NAME, --name NAME  Your app's/project's name.
  -a AUTHOR, --author AUTHOR
                        Your name.
  -e EMAIL, --email EMAIL
                        Your email address.
  -l LICENSE, --license LICENSE
                        License shortname e.g. gpl2.
  -lang LANGUAGE, --language LANGUAGE
                        The project language.
  -t PTYPE, --type PTYPE
                        The ptype of project e.g. cli, web.
  -vcs VCS, --version-control-system VCS
                        Version Control
  -p PARENT, --parent-dir PARENT
                        The parent directory e.g. ~/projects.
  -f FOOTPRINT, --footprint FOOTPRINT
                        Provide a custom footprint.
```

**Comment by darthlukan** [comment]
Is the `~/build/swift` arg you provided a directory or a file? Does it exist? I just used your Swift footprint to create a project by issuing the the following:

```
python main.py -f ~/projects/progeny-footprints/swift/cli -n my_app -p ~/tmp
```

The result was:

```
VCS init failure.
The following errors were encountered:
VCS init failure.
my_app was generated successfully.
```

I then verified that the project was actually created, and all files and folders specified in your footprint were there.

Do you have a `~/.progenyrc` file? The validator checks for a config before parsing the args of a footprint, which now that I think about it, is probably not the best thing to do. Try creating a config file and running it again. In the meantime, I'll figure out how I can safely separate the config requirement from the footprint check.

**Comment by AdrianKoshka** [comment]
I copied the default progenyrc file included with the repo to ~/.progenyrc . After doing such I again tried to prep the project. 

``` bash
$ python3 main.py -f ~/git/github/adrian/progeny-footprints/swift/cli -n my_app -p ~/build/swift
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    main()
  File "main.py", line 316, in main
    project_state = project.generate()
  File "main.py", line 265, in generate
    print(self._errors[-1].message)
AttributeError: 'RuntimeError' object has no attribute 'message'
```

Though upon checking ~/build/swift/ (which is a directory not a file and does exist) it seemed all files were there

``` bash
$ ls -l ~/build/swift/my_app/*  
-rw-rw-r-- 1 adrian adrian 18092 Dec  9 21:28 /home/adrian/build/swift/my_app/LICENSE
-rw-rw-r-- 1 adrian adrian     0 Dec  9 21:28 /home/adrian/build/swift/my_app/Package.swift
-rw-rw-r-- 1 adrian adrian   120 Dec  9 21:28 /home/adrian/build/swift/my_app/README.md

/home/adrian/build/swift/my_app/sources:
total 0
-rw-rw-r-- 1 adrian adrian 0 Dec  9 21:28 main.swift
```

SO now it makes the files/folders, **_BUT**_ still outputs errors.
